services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "${PWD}/setup.sh:/etc/localstack/init/ready.d/setup.sh"
      - "${PWD}/src:/tmp/src"      
